# Generated by Django 5.0.1 on 2024-02-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0003_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="given_name",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["given_name", "last_name"],
                name="store_custo_given_n_1a7060_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
