# Generated by Django 5.0.1 on 2024-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0004_rename_first_name_customer_given_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_given_n_1a7060_idx",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="given_name",
            new_name="first_name",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="store_custo_first_n_a7e990_idx",
            ),
        ),
    ]
