# Generated by Django 5.0.1 on 2024-02-03 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0005_remove_customer_store_custo_given_n_1a7060_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL("""
         INSERT INTO playground_collection (title)
         VALUES ('collection1');
        """,
                          """
        DELETE FROM playground_collection WHERE title = 'collection1';
        """
                          )
    ]
